vim.api.nvim_set_hl(0, 'Normal', { ctermfg = 'none', fg = '#C4C6CD', bg = 'none' })
vim.api.nvim_set_hl(0, 'NormalNC', { ctermfg = 'none', fg = '#C4C6CD', bg = 'none' })
vim.api.nvim_set_hl(0, 'NvimTreeNormal', { bg = 'none' })
vim.api.nvim_set_hl(0, 'WinSeparator', { fg = '#C4C6CD', bg = 'none' })
vim.api.nvim_set_hl(0, 'NvimTreeWinSeparator', { fg = '#C4C6CD', bg = 'none' })
vim.api.nvim_set_hl(0, 'TreesitterContext', { bg = '#1e1e2e' })
vim.api.nvim_set_hl(0, 'TreesitterContextLineNumber', { bg = '#1e1e2e', fg = '#f9e2af' })
vim.api.nvim_set_hl(0, 'TreesitterContextBottom', { bg = 'none', fg = 'none' })
-- vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#A6DBFF' }) -- NvimLightBlue
-- vim.api.nvim_set_hl(0, 'LineNr', { fg = '#C4C6CD' })
vim.api.nvim_set_hl(0, 'NormalFloat', { bg = 'none' })
vim.api.nvim_set_hl(0, 'FloatBorder', { bg = 'none' })
