-- vim.cmd 'highlight ColorColumn guibg=#1e1e2e'
vim.cmd 'highlight Normal ctermfg=none guifg=none guibg=none'
vim.cmd 'highlight NormalNC ctermfg=none guifg=none guibg=none'
vim.cmd 'highlight NvimTreeNormal guibg=none'
vim.cmd 'highlight TreesitterContext guibg=none'
-- vim.cmd 'highlight TreesitterContextSeparator guifg=#f9e2af'
vim.cmd 'highlight TreesitterContextLineNumber guibg=#f9e2af'
-- vim.cmd 'highlight TreesitterContextLineNumberBottom guifg=#f9e2af gui=underline'
vim.cmd 'highlight TreesitterContextBottom gui=none'
vim.cmd 'highlight CursorLineNr guifg=#b4befe'
vim.cmd 'highlight LineNr guifg=#7f849c'
vim.cmd 'highlight NvimTreeWinSeparator guifg=#7f849c guibg=none'
vim.cmd 'highlight WinSeparator guifg=#7f849c guibg=none'
vim.cmd 'highlight NormalFloat guibg=#1e1e2e'
-- vim.cmd 'highlight FloatBorder guibg=none'
