return {
  -- {
  --   'AlexvZyl/nordic.nvim',
  --   lazy = false,
  --   priority = 1000,
  --   config = function()
  --     require('nordic').load()
  --   end,
  -- },
  -- {
  --   'shaunsingh/nord.nvim',
  --   config = function()
  --     -- Example config in lua
  --     vim.g.nord_contrast = true
  --     vim.g.nord_borders = false
  --     vim.g.nord_disable_background = true
  --     vim.g.nord_italic = false
  --     vim.g.nord_uniform_diff_background = true
  --     vim.g.nord_bold = false
  --
  --     -- Load the colorscheme
  --     require('nord').set()
  --   end,
  -- },
  -- {
  --   'rose-pine/neovim',
  --   config = function()
  --     require('rose-pine').setup {
  --       variant = 'auto', -- auto, main, moon, or dawn
  --       dark_variant = 'main', -- main, moon, or dawn
  --       dim_inactive_windows = false,
  --       extend_background_behind_borders = true,
  --
  --       enable = {
  --         terminal = true,
  --         legacy_highlights = true, -- Improve compatibility for previous versions of Neovim
  --         migrations = true, -- Handle deprecated options automatically
  --       },
  --
  --       styles = {
  --         bold = true,
  --         italic = false,
  --         transparency = false,
  --       },
  --
  --       groups = {
  --         border = 'muted',
  --         link = 'iris',
  --         panel = 'surface',
  --
  --         error = 'love',
  --         hint = 'iris',
  --         info = 'foam',
  --         note = 'pine',
  --         todo = 'rose',
  --         warn = 'gold',
  --
  --         git_add = 'foam',
  --         git_change = 'rose',
  --         git_delete = 'love',
  --         git_dirty = 'rose',
  --         git_ignore = 'muted',
  --         git_merge = 'iris',
  --         git_rename = 'pine',
  --         git_stage = 'iris',
  --         git_text = 'rose',
  --         git_untracked = 'subtle',
  --
  --         h1 = 'iris',
  --         h2 = 'foam',
  --         h3 = 'rose',
  --         h4 = 'gold',
  --         h5 = 'pine',
  --         h6 = 'foam',
  --       },
  --     }
  --   end,
  -- },
  -- {
  --   'catppuccin/nvim',
  --   name = 'catppuccin',
  --   priority = 1000,
  --   config = function()
  --     require('catppuccin').setup {
  --       flavour = 'mocha', -- latte, frappe, macchiato, mocha
  --       integrations = {
  --         native_lsp = {
  --           enabled = true,
  --           virtual_text = {
  --             errors = {},
  --             hints = {},
  --             warnings = {},
  --             information = {},
  --           },
  --           underlines = {
  --             errors = { 'undercurl' },
  --             hints = { 'undercurl' },
  --             warnings = { 'undercurl' },
  --             information = { 'undercurl' },
  --           },
  --         },
  --       },
  --     }
  --   end,
  -- },
}
