[env]
TERM = "xterm-256color"

[font]
size = 15
offset.y = 3

[font.normal]
# family = "GeistMono Nerd Font Mono"
family = "JetBrainsMono Nerd Font Mono"
# style = "ExtraLight"
# family = "MonoLisa Nerd Font Mono"
# family = "SFMono Nerd Font Mono"
# family = "MesloLGL Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"
# family = "FiraCode Nerd Font Mono"
# style = "Light"

[terminal.shell]
program = "/bin/zsh"

[window]
opacity = 0.95
decorations = "None"
option_as_alt = "Both"

[window.padding]
x = 0
y = 0

# https://github.com/nshern/neovim-default-colorscheme-extras/blob/main/extras/alacritty/nvim-dark.toml
# TODO: PR to https://github.com/alacritty/alacritty-theme/
[colors.primary]
background = "#14161b"
foreground = "#E0E2EA"
dim_foreground = "#C4C6CD"
bright_foreground = "#E0E2EA"

[colors.cursor]
text = "#14161b"
cursor = "#E0E2EA"

[colors.vi_mode_cursor]
text = "#14161b"
cursor = "#E0E2EA"

[colors.search.matches]
foreground = "#14161b"
background = "#4f5258"

[colors.search.focused_match]
foreground = "#14161b"
background = "#7EDFDE"

[colors.footer_bar]
foreground = "#14161b"
background = "#7EDFDE"

[colors.hints.start]
foreground = "#14161b"
background = "#E5ADB9"

[colors.hints.end]
foreground = "#14161b"
background = "#7EDFDE"

[colors.selection]
text = "#E0E2EA"
background = "#4f5258"

[colors.normal]
black = "#2c2e33"
red = "#E5ADB9"
green = "#A2DFC0"
yellow = "#E3CA85"
blue = "#95C5E5"
magenta = "#E5B6E6"
cyan = "#7EDFDE"
white = "#C4C6CD"

[colors.bright]
black = "#4f5258"
red = "#FFC0B9"
green = "#B4F6C0"
yellow = "#FCE094"
blue = "#A6DBFF"
magenta = "#FFCAFF"
cyan = "#8CF8F7"
white = "#9b9ea4"

[colors.dim]
black = "#2c2e33"
red = "#E5ADB9"
green = "#A2DFC0"
yellow = "#E3CA85"
blue = "#95C5E5"
magenta = "#E5B6E6"
cyan = "#7EDFDE"
white = "#C4C6CD"

[[colors.indexed_colors]]
index = 16
color = "#7EDFDE"

[[colors.indexed_colors]]
index = 17
color = "#4f5258"

