#!/bin/bash

# This thing
sudo pacman -S --needed base-devel

# Install packages
yay -S --noconfirm --needed \
    stow \
    tmux \
    zsh \
    go \
    brave-browser \
    nodejs \
    ghostty

# Remove
rm -rf ~/projects/dots
rm -rf ~/projects/LazyVim

# Clone
mkdir -p ~/projects
cd projects
git clone https://github.com/peterszarvas94/dots.git
git clone https://github.com/peterszarvas94/omarchy-nvim-theme-grabber.git

# Origin
cd ~/projects/LazyVim
git remote remove origin 2>/dev/null || true
git remote add origin git@github.com:peterszarvas94/omarchy-nvim-theme-grabber.git

cd ~/projects/dots
git remote remove origin 2>/dev/null || true
git remote add origin git@github.com:peterszarvas94/dots.git

# Config packages (TODO: wayland stuff)
./config --os=omarchy

ln -nsf ~/.config/omarchy/current/theme/neovim.lua ~/.config/nvim/lua/plugins/theme.lua
ln -nsf ~/.config/omarchy/current/theme/alacritty.toml ~/.config/alacritty/theme.toml
ln -nsf ~/.config/alacritty/omarchy.toml ~/.config/alacritty/platform.toml
ln -nsf ~/.config/omarchy/current/theme/ghostty.conf ~/.config/ghostty/theme.toml

hyprctl reload
