#!/bin/bash

# Clone dots
rm -rf ~/projects/dots
rm -rf ~/projects/LazyVim

mkdir -p ~/projects
git clone --depth 1 https://github.com/peterszarvas94/dots.git ~/projects/dots
cd projects/dots

# This thing
sudo pacman -S --needed base-devel

# Install packages
yay -S --noconfirm --needed \
    stow \
    tmux \
    zsh \
    go \
    brave-browser \
    nodejs

# Config packages (TODO: wayland stuff)
./config --os=omarchy

# Clone theme grabber and link theme file
git clone --depth 1 https://github.com/peterszarvas94/omarchy-nvim-theme-grabber.git ~/projects/LazyVim

ln -nsf ~/.config/omarchy/current/theme/neovim.lua ~/.config/nvim/lua/plugins/theme.lua
ln -nsf ~/.config/omarchy/current/theme/alacritty.toml ~/.config/alacritty/theme.toml
ln -nsf ~/.config/alacritty/omarchy.toml ~/.config/alacritty/platform.toml

hyprctl reload
