#!/bin/bash

# This thing
sudo pacman -S --needed base-devel

# Install packages
yay -S --noconfirm --needed \
    stow \
    tmux \
    zsh \
    go \
    brave-browser \
    nodejs \
    ghostty

# Remove
rm -rf ~/projects/dots
rm -rf ~/projects/LazyVim

# Clone
mkdir -p ~/projects
cd projects
git clone https://github.com/peterszarvas94/dots.git
git clone https://github.com/peterszarvas94/omarchy-nvim-theme-grabber.git LazyVim

# Origin
cd ~/projects/LazyVim
git remote remove origin 2>/dev/null || true
git remote add origin git@github.com:peterszarvas94/omarchy-nvim-theme-grabber.git

cd ~/projects/dots
git remote remove origin 2>/dev/null || true
git remote add origin git@github.com:peterszarvas94/dots.git

./config --os=omarchy
