#!/bin/bash

# Clone dots
mkdir -p ~/projects
git clone https://github.com/peterszarvas94/dots.git ~/projects/dots
cd projects/dots

# Install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install packages
brew tap homebrew/cask-fonts
brew install \
    stow \
    tmux \
    zsh \
    go \
    font-jetbrains-mono-nerd-font \
    brave-browser \
    node

# Config packages 
./config --os=mac

# Link platform-specific alacritty config
ln -nsf ~/.config/nvim/theme_default.lua ~/.config/nvim/lua/plugins/theme.lua
ln -nsf ~/.config/alacritty/theme_default.toml ~/.config/alacritty/theme.toml
ln -nsf ~/.config/alacritty/mac.toml ~/.config/alacritty/platform.toml
