#!/bin/bash

# Install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install packages
brew tap homebrew/cask-fonts
brew install \
    stow \
    tmux \
    zsh \
    go \
    brave-browser \
    node \
    ghostty

# Remove
rm -rf ~/projects/dots
rm -rf ~/projects/LazyVim

# Clone
mkdir -p ~/projects
cd projects
git clone https://github.com/peterszarvas94/dots.git
git clone https://github.com/peterszarvas94/omarchy-nvim-theme-grabber.git

# Origin
cd ~/projects/LazyVim
git remote remove origin 2>/dev/null || true
git remote add origin git@github.com:peterszarvas94/omarchy-nvim-theme-grabber.git

cd ~/projects/dots
git remote remove origin 2>/dev/null || true
git remote add origin git@github.com:peterszarvas94/dots.git

# Config packages 
./config --git --pkg=all --theme
