#!/bin/bash

# Install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install packages
brew tap homebrew/cask-fonts
brew install \
    stow \
    tmux \
    zsh \
    go \
    brave-browser \
    node \
    ghostty

# Remove
rm -rf ~/projects/dots
rm -rf ~/projects/LazyVim

# Clone
mkdir -p ~/projects
git clone https://github.com/peterszarvas94/dots.git ~/projects/dots
git clone https://github.com/peterszarvas94/omarchy-nvim-theme-grabber.git ~/projects/LazyVim

# Origin
cd "$HOME/projects/LazyVim"
git remote remove origin 2>/dev/null || true
git remote add origin git@github.com:peterszarvas94/omarchy-nvim-theme-grabber.git

cd "$HOME/projects/dots"
git remote remove origin 2>/dev/null || true
git remote add origin git@github.com:peterszarvas94/dots.git

# Config packages 
./config --os=mac

# Link platform-specific alacritty config
ln -nsf ~/.config/nvim/theme_default.lua ~/.config/nvim/lua/plugins/theme.lua
ln -nsf ~/.config/alacritty/theme_default.toml ~/.config/alacritty/theme.toml
ln -nsf ~/.config/alacritty/mac.toml ~/.config/alacritty/platform.toml
ln -nsf ~/.config/ghostty/default_theme.conf ~/.config/ghostty/theme.conf
