return {
  --   'nvim-lualine/lualine.nvim',
  --   dependencies = {
  --     'nvim-tree/nvim-web-devicons',
  --     -- 'AndreM222/copilot-lualine',
  --   },
  --   config = function()
  --     require('lualine').setup {
  --       options = {
  --         component_separators = { left = '', right = '' },
  --         section_separators = { left = '', right = '' },
  --       },
  --       sections = {
  --         -- lualine_c = {},
  --         lualine_x = { --[[ 'copilot', ]] 'encoding', 'fileformat', 'filetype' },
  --       },
  --       tabline = {
  --         lualine_a = {
  --           {
  --             'tabs',
  --             tab_max_length = vim.o.columns,
  --             max_length = vim.o.columns,
  --             use_mode_colors = true,
  --             mode = 1,
  --             path = 1,
  --             symbols = {
  --               modified = '',
  --             },
  --           },
  --         },
  --       },
  --     }
  --   end,
}
