return {
  --   'catppuccin/nvim',
  --   name = 'catppuccin',
  --   priority = 1000,
  --   config = function()
  --     -- require('catppuccin').setup {
  --     --   flavour = 'mocha', -- latte, frappe, macchiato, mocha
  --     --   integrations = {
  --     --     native_lsp = {
  --     --       enabled = true,
  --     --       virtual_text = {
  --     --         errors = {},
  --     --         hints = {},
  --     --         warnings = {},
  --     --         information = {},
  --     --       },
  --     --       underlines = {
  --     --         errors = { 'undercurl' },
  --     --         hints = { 'undercurl' },
  --     --         warnings = { 'undercurl' },
  --     --         information = { 'undercurl' },
  --     --       },
  --     --     },
  --     --   },
  --     -- }
  --
  --     -- Set the colorscheme
  --     vim.cmd.colorscheme 'catppuccin'
  --   end,
}
