-- vim.api.nvim_set_hl(0, "ColorColumn", { bg = "#1e1e2e" })
vim.api.nvim_set_hl(0, 'Normal', { ctermfg = 'none', fg = 'none', bg = 'none' })
vim.api.nvim_set_hl(0, 'NormalNC', { ctermfg = 'none', fg = 'none', bg = 'none' })
vim.api.nvim_set_hl(0, 'NvimTreeNormal', { bg = 'none' })
vim.api.nvim_set_hl(0, 'NvimTreeWinSeparator', { fg = '#7f849c', bg = 'none' })
vim.api.nvim_set_hl(0, 'TreesitterContext', { bg = 'none' })
-- vim.api.nvim_set_hl(0, "TreesitterContextSeparator", { fg = "#f9e2af" })
vim.api.nvim_set_hl(0, 'TreesitterContextLineNumber', { bg = '#f9e2af', fg = '#1e1e2e' })
-- vim.api.nvim_set_hl(0, "TreesitterContextLineNumberBottom", { fg = "#f9e2af", gui = "underline" })
vim.api.nvim_set_hl(0, 'TreesitterContextBottom', {})
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#b4befe' })
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#7f849c' })
vim.api.nvim_set_hl(0, 'WinSeparator', { fg = '#7f849c', bg = 'none' })
vim.api.nvim_set_hl(0, 'NormalFloat', { bg = 'none' })
vim.api.nvim_set_hl(0, 'FloatBorder', { bg = 'none', fg = '#89b4fa' })
