onboarding = false
# herdr configuration
# Place this file at ~/.config/herdr/config.toml

[theme]
name = "rose-pine"
auto_switch = false

[keys]
detach = "prefix+d"
settings = "prefix+period"
goto = "prefix+s"
navigate_workspace_up = ["k", "up"]
navigate_workspace_down = ["j", "down"]
rename_tab = "prefix+comma"
previous_workspace = "prefix+p"
next_workspace = "prefix+n"
previous_tab = ""
next_tab = ""

[ui]
agent_panel_sort = "spaces"
show_agent_labels_on_pane_borders = true
