vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.o.guicursor = "n-v-c:block"
vim.o.hlsearch = false
vim.o.number = true
vim.o.relativenumber = true
vim.o.cursorline = true
vim.o.mouse = 'a'
vim.o.clipboard = 'unnamedplus'
vim.o.undofile = true
vim.o.signcolumn = 'yes'
vim.o.colorcolumn = ''
vim.o.termguicolors = true
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.expandtab = true
vim.g.netrw_liststyle = 0
vim.o.scrolloff = 8
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.inccommand = "split"
vim.o.swapfile = false
vim.o.conceallevel = 2

-- vim.o.breakindent = true
-- vim.o.updatetime = 250
-- vim.o.timeout = true
-- vim.o.timeoutlen = 300
-- vim.o.completeopt = 'menuone,noselect'
