import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

[shell]
program = "/bin/zsh"

[window]
opacity = 1

[window.padding]
x = 10
y = 10
