import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
# family = "GeistMono Nerd Font Mono"
# family = "JetBrainsMono Nerd Font Mono"
# style = "ExtraLight"
# family = "MonoLisa Nerd Font Mono"
# family = "SFMono Nerd Font Mono"
family = "MesloLGS Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"
# family = "FiraCode Nerd Font Mono"
# style = "Light"

[shell]
program = "/bin/zsh"

[window]
opacity = 1
decorations = "none"

[window.padding]
x = 10
y = 10
