start-at-login = true
default-root-container-layout = 'tiles'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 8
    inner.vertical =   8
    outer.left =       8
    outer.bottom =     8
    outer.top =        8
    outer.right =      8

[mode.main.binding]
    ctrl-minus = 'resize height -50'
    ctrl-equal = 'resize height +50'
    ctrl-period= 'resize width -50'
    ctrl-comma= 'resize width +50'
    cmd-semicolon = 'focus --dfs-index 1'

    ctrl-1 = 'workspace 1'
    ctrl-2 = 'workspace 2'
    ctrl-3 = 'workspace 3'
    ctrl-4 = 'workspace 4'
    ctrl-5 = 'workspace 5'
    ctrl-6 = 'workspace 6'
    ctrl-7 = 'workspace 7'
    ctrl-8 = 'workspace 8'
    ctrl-9 = 'workspace 9'
    ctrl-0 = 'workspace 10'

    ctrl-shift-1 = 'move-node-to-workspace 1'
    ctrl-shift-2 = 'move-node-to-workspace 2'
    ctrl-shift-3 = 'move-node-to-workspace 3'
    ctrl-shift-4 = 'move-node-to-workspace 4'
    ctrl-shift-5 = 'move-node-to-workspace 5'
    ctrl-shift-6 = 'move-node-to-workspace 6'
    ctrl-shift-7 = 'move-node-to-workspace 7'
    ctrl-shift-8 = 'move-node-to-workspace 8'
    ctrl-shift-9 = 'move-node-to-workspace 9'
    ctrl-shift-0 = 'move-node-to-workspace 10'

    cmd-shift-semicolon = 'mode service'

    ctrl-shift-h = 'move left'
    ctrl-shift-j = 'move down'
    ctrl-shift-k = 'move up'
    ctrl-shift-l = 'move right'

    ctrl-alt-h = 'focus left'
    ctrl-alt-j = 'focus down'
    ctrl-alt-k = 'focus up'
    ctrl-alt-l = 'focus right'

    cmd-alt-h = 'join-with left'
    cmd-alt-j = 'join-with down'
    cmd-alt-k = 'join-with up'
    cmd-alt-l = 'join-with right'

    # cmd-enter = 'exec-and-forget open -n /Applications/Ghostty.app'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout

# [[on-window-detected]]
#     if.app-id = 'com.apple.systempreferences'
#     if.app-name-regex-substring = 'settings'
#     if.window-title-regex-substring = 'substring'
#     if.workspace = 'workspace-name'
#     if.during-aerospace-startup = true
#     check-further-callbacks = true
#     run = ['layout floating', 'move-node-to-workspace S']  # The callback itself

[[on-window-detected]]
    if.app-name-regex-substring = 'Settings'
    run = [ "layout floating" ]

[[on-window-detected]]
    if.window-title-regex-substring = 'Teams'
    run = [ "layout floating" ]

[[on-window-detected]]
    if.window-title-regex-substring = 'Calculator'
    run = [ "layout floating" ]

[[on-window-detected]]
    if.app-name-regex-substring = 'Finder'
    run = [ "layout floating" ]

[[on-window-detected]]
    if.app-name-regex-substring = 'Preview'
    run = [ "layout floating" ]

[[on-window-detected]]
    if.app-name-regex-substring = 'DBeaver'
    run = [ "layout floating" ]

[[on-window-detected]]
    if.app-name-regex-substring = 'Google Chrome'
    run = [ "layout floating" ]

[workspace-to-monitor-force-assignment]
    10 = '^built-in retina display$'
