# sudo echo "{}" > /opt/homebrew/Caskroom/amethyst/0.21.1/Amethyst.app/Contents/Resources/default.amethyst

layouts:
  - floating

mod1:
  - shift
  - control

# Focus the next window in the list going counter-clockwise.
focus-ccw:
  mod: mod1
  key: j

# Focus the next window in the list going clockwise.
focus-cw:
  mod: mod1
  key: k

throw-space-1:
  mod: mod1
  key: "1"

throw-space-2:
  mod: mod1
  key: "2"

throw-space-3:
  mod: mod1
  key: "3"

throw-space-4:
  mod: mod1
  key: "4"

throw-space-5:
  mod: mod1
  key: "5"

throw-space-6:
  mod: mod1
  key: "6"

throw-space-7:
  mod: mod1
  key: "7"

throw-space-8:
  mod: mod1
  key: "8"

throw-space-9:
  mod: mod1
  key: "9"

throw-space-10:
  mod: mod1
  key: "0"

throw-space-left:
  mod: mod1
  key: l 

throw-space-right:
  mod: mod1
  key: h 

mouse-follows-focus: true

relaunch-amethyst:
  mod: mod1
  key: z

